### ISSUE TITLE
color options?

### ISSUE THREAD

**Issue by jnormen** [sindresorhus/gulp-debug#13]
Hi, 

Really nice plugin. 
I see others want options for coloring outputs? It's not that hard wto add it hen people just ask for it? 
I know I can change the color on my terminal but using others tools that cannot. Like Task Explorer on Visual Studio. I think it would be a nice future for UX perspective to send out debugs in different colors for different titles. I know you don't like it but it's an easy feature for you to add when ppl gladly ask for it right? It would be so awsome. 

thanx, keep up the good work.

**Comment by sindresorhus** [comment]
It's also fixing it at the wrong abstraction. This way you'll have to open the same useless issue on every tool you use. Thanks the suggestion though ;)

**Comment by jack4it** [comment]
Where is the recommended abstraction then to change the output color of this tool?

**Comment by sindresorhus** [comment]
Your terminal. The color is defined as blue. It's up to your terminal to pick what kind of blue. You can change this in most terminals.

**Comment by jack4it** [comment]
Failed to figure out how I can do this for Windows console. Any ideas? Thanks!

**Comment by sindresorhus** [comment]
Use a better terminal like http://cmder.net/
