### ISSUE TITLE
Prevent `gulp-debug` to show "0 items" when used with `gulp-if`

### ISSUE THREAD

**Issue by laurentgoudet** [sindresorhus/gulp-debug#18]
Let's say I want to show `gulp` pipes debug info only when a flag is enabled:

```
...
.pipe(if(configs.debug, debug({title: 'js'})))
...
```

Is there a way to prevent `gulp-debug` to show `0 items` when if condition is false? The issue is that `debug` is going to be instantiated no matter what, but no files are going to pass through, hence the `0 items`. I've tried to play with `lazypipe` but it feels hacky.

For now I have disabled the output when `count` is zero, but I was wondering if there was a better solution for that.

**Comment by sindresorhus** [comment]
Sounds like a problem you should take up with `gulp-if`. It shouldn't use the stream if the condition doesn't match.

**Comment by Saturn2888** [comment]
https://github.com/sindresorhus/gulp-filter/issues/56

**Comment by nfroidure** [comment]
@laurentgoudet with `gulp-cond`, you can pass stream generators in and avoid instantiating the stream when not needed. It would give:
```js
...
    .pipe(cond(configs.debug, debug.bind(null, {title: 'js'})))
...
```

**Comment by robertmain** [comment]
[I'm using `gulp-if` and `gulp-debug` together and not seeing this issue for some reason](https://github.com/robertmain/pillars/blob/master/gulp/tasks/compile-style.js#L33)

**Comment by robertmain** [comment]
[I'm using `gulp-if` and `gulp-debug` together and not seeing this issue for some reason](https://github.com/robertmain/pillars/blob/master/gulp/tasks/compile-style.js#L33)
