### ISSUE TITLE
Enumeration

### ISSUE THREAD

**Issue by FranzSkuffka** [sindresorhus/gulp-debug#22]
Is it possible to enumerate the printed files?

**Comment by sindresorhus** [comment]
Enumerate in what way? Be more specific about what you're looking for.

**Comment by FranzSkuffka** [comment]
Thank you for the feedback.
It would be nice if I could pass gulp-debug the option to post/prefix the title. The prefix should be the ordinal number starting at 0 with the first and incremented before each logged file.

**Comment by sindresorhus** [comment]
Why? For what purpose? The stream isn't in order anyways.
