### ISSUE TITLE
Only Filenames

### ISSUE THREAD

**Issue by aeolingamenfel** [sindresorhus/gulp-debug#23]
It would be nice if there were a mode where it only outputs a list of the files names (minus any paths to the files), or relative filesnames beyond a certain base.

###### No base
Config: `{base: '', title: 'unicorn'}`

Output (windows FS): 
```
unicorn Testing\style.css
unicorn Testing\sass\style.scss
```

###### With Base
Config: `{base: 'Testing/', title: 'unicorn'}`

Output (windows FS):
```
unicorn style.css
unicorn sass\style.scss
```

**Comment by sindresorhus** [comment]
No thanks
