### ISSUE TITLE
Suggestion: ability to turn on/off debug logging

### ISSUE THREAD

**Issue by dgreene1** [sindresorhus/gulp-debug#25]
Hi. Gulp-debug is one of the coolest things I've ever seen. I am absolutely in love. Thank you for building this.

One small suggestion. Could we provide the ability to turn on and off the debug logging with a flag like:
```
gulp -debug-off [task-name]
```

**Comment by sindresorhus** [comment]
Nah, this task isn't meant to be used permanently, but rather for debugging. You can use `gulp-if` and check the cli flag yourself if you want this.
