### ISSUE TITLE
stat logging as [object Object] with --verbose

### ISSUE THREAD

**Issue by donabrams** [sindresorhus/gulp-debug#30]
I traced this down to use of is-plain-obj in stringify-object; The stat object definitely extends some prototype now:

```
> Object.getPrototypeOf(file.stat)
{ _checkModeProperty: [Function],
  isDirectory: [Function],
  isFile: [Function],
  isBlockDevice: [Function],
  isCharacterDevice: [Function],
  isSymbolicLink: [Function],
  isFIFO: [Function],
  isSocket: [Function] }
```

I'm not sure why stringify-object is restricted to plain objects. Related issue (closed, unresolved) in stringify-object: https://github.com/yeoman/stringify-object/issues/26

**Comment by sindresorhus** [comment]
I don't remember exactly, but a PR on `stringify-object` using https://github.com/sindresorhus/is-obj instead would be welcomed ;)

**Comment by nicolaiskogheim** [comment]
So if I understand this correctly:

Replacing [this call to `isPlainObj`](https://github.com/yeoman/stringify-object/blob/master/index.js#L79) with a call to `isObj` would enable printing of non-plain objects? And that's it?
