### ISSUE TITLE
support --SILENT mode

### ISSUE THREAD

**Issue by WuglyakBolgoink** [sindresorhus/gulp-debug#35]
is it possible to do silent mode for gulp-debug?

see https://github.com/gulpjs/gulp/issues/499

**Comment by sindresorhus** [comment]
This module uses gulpUtil.log for logging, so it should be possible as explained in https://github.com/gulpjs/gulp/issues/499#issuecomment-93824634. If not, open an issue on https://github.com/gulpjs/gulp-util.
