### ISSUE TITLE
peerinvalid Peer gulp-debug@4.0.0 wants gulp@>=4

### ISSUE THREAD

**Issue by lzl124631x** [sindresorhus/gulp-debug#44]
I met this error when `npm install gulp-debug`
```
peerinvalid Peer gulp-debug@4.0.0 wants gulp@>=4
```

The latest gulp version is `3.9.1`. How can I install gulp@>=4?

I have to `npm install gulp-debug@3`

**Comment by sindresorhus** [comment]
https://github.com/gulpjs/gulp/releases/tag/v4.0.0

**Comment by lzl124631x** [comment]
@sindresorhus Weird. I can only get 3.9.1 with `npm install gulp@latest`.
