### ISSUE TITLE
Chokidar v2 dependency no longer valid for Node.js v14+?

### ISSUE THREAD

**Issue by TotallyInformation** [sindresorhus/gulp-debug#48]
![image](https://user-images.githubusercontent.com/1591850/147656927-7c0420ca-96df-46fa-8876-fe38deed5c0e.png)

![image](https://user-images.githubusercontent.com/1591850/147656945-92c356e5-8ad9-4962-a95d-e768fbfe56bc.png)

**Comment by sindresorhus** [comment]
Chokidar is not a dependency of this package. (You could have easily confirmed this yourself)

**Comment by TotallyInformation** [comment]
Well that is why I used `npm explain` - it is listed in the tree.
